apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: ambulance-project-webapi
  namespace: wac-hospital
spec:
  image: michalsorat/ambulance-project-webapi
  interval: 1m0s