apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: wac-hospital  # chceme tieto objekty umiestniť do `wac-hospital` namespace
                         # tento zapis preťaží hodnoty "namespace" vo všetkých objektoch


commonLabels:
  app.kubernetes.io/part-of: wac-hospital

resources:
- ../../../apps/ms-ambulance-ufe
- ../../../apps/xsorat-ambulance-project-webapi

##add new line here

components:
 - ../../../components/version-developers
 - https://github.com/michalsorat/ambulance-project-webapi/deployments/kustomize/components/mongodb

patches:
 - path: patches/ambulance-webapi.service.yaml