apiVersion: apps/v1
kind: Deployment
metadata:
  name: xsorat-ambulance-project-webapi
spec:
  template:
    spec:
      containers:
        - name: openapi-ui
          env:
            - name: URL
              value: /xsorat-openapi
            - name: BASE_URL
              value: /xsorat-openapi-ui