apiVersion: fe.milung.eu/v1
kind: WebComponent
metadata:
  name: xsorat-ambulance-project
spec:
  module-uri: http://xsorat-ambulance-project.wac-hospital/build/ambulance-project.esm.js
                     # module web komponentu pre tento mikroFE
                     # - umiestnený v namespace wac-hospital
  navigation:
    - element: ambulance-app  # element, ktorý bude vložený na stránku
                                    # pri navigácii na zoznam čakajúcich
      path: xsorat-ambulance-project      # cesta, ktora sa zobrazi v address bare v prehliadaci, ked bude tento mikroFE aktívny
      title: Objednávací systém- xsorat      # názov mikro aplikácie
      details: Spravuje objednávky špecifických diétnych stráv založených na medicínskych požiadavkách alebo zdravotných stavoch pacientov. 
  preload: false                    # určuje, či má byť web komponent načítaný spolu s hlavnou stránkou
  proxy: true                       # pre komponenty v rámci klastra, neprístupné na verejnej sieti
                                    # musí byť táto hodnota nastavená na true
  hash-suffix: v1alpha9             # voliteľný suffix pre načítanie modulu web komponentu - jeho zmenou
                                    # sa mení názov URL pre modul a tým je možné predísť problémom
                                    # s verziami vo vyrovnávacích pamätiach