apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- 'https://github.com/michalsorat/ambulance-project-webapi//deployments/kustomize/install' # ?ref=v1.0.1
- 'https://github.com/milung/ambulance-webapi//deployments/kustomize/install' # ?ref=v1.0.1
- http-route.yaml

patches:
- path: patches/ambulance-webapi.deployment.yaml